# this gets the automatic subdirectory inclusion, but can't produce a single pdf, only one per file
project:
  type: website

website:
  title: "Website"
  sidebar:
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



